spring:
  name: ComputerStore

  flyway: baseline-on-migrate=true

  datasource:
    url: jdbc:h2:mem:h-basic;DB_CLOSE_DELAY=-1
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
